services:
  kafka-1:
    image: apache/kafka:latest
    container_name: kafka-1
    ports:
      - "19092:19092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-1:9092,EXTERNAL://localhost:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "2"
      KAFKA_LOG_DIRS: "/opt/kafka/data"
    volumes:
      - kafka1-data:/tmp/kraft-combined-logs
    networks:
      - app-network

  kafka-2:
    image: apache/kafka:latest
    container_name: kafka-2
    ports:
      - "19093:19093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19093,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-2:9092,EXTERNAL://localhost:19093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "2"
      KAFKA_LOG_DIRS: "/opt/kafka/data"
    volumes:
      - kafka2-data:/tmp/kraft-combined-logs
    networks:
      - app-network

  kafka-3:
    image: apache/kafka:latest
    container_name: kafka-3
    ports:
      - "19094:19094"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19094,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-3:9092,EXTERNAL://localhost:19094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "3"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "2"
      KAFKA_LOG_DIRS: "/opt/kafka/data"
    volumes:
      - kafka3-data:/tmp/kraft-combined-logs
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: default
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-1:8083
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  redis-master:
    image: bitnami/redis:latest
    container_name: redis-master
    ports:
      - "6378:6378"
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-master-data:/bitnami/redis/data
    networks:
      - app-network

  redis-replica-1:
    image: bitnami/redis:latest
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis-master
    networks:
      - app-network

  redis-replica-2:
    image: bitnami/redis:latest
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis-master
    networks:
      - app-network

  redis-sentinel-1:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_MASTER_SET=mymaster
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - app-network

  redis-sentinel-2:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_MASTER_SET=mymaster
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - app-network

  redis-sentinel-3:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_MASTER_SET=mymaster
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - app-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - app-network

  # node-app:
  #   build: .
  #   container_name: e-root-ms
  #   ports:
  #     - "3100:3100"
  #   depends_on:
  #     - redis-master
  #     - redis-sentinel-1
  #     - redis-sentinel-2
  #     - redis-sentinel-3
  #     - kafka-1
  #     - kafka-2
  #     - kafka-3
  #   environment:
  #     - MONGODB_URI=mongodb://mongodb:27017
  #     - MONGODB_DB_NAME=orders_db
  #     - REDIS_SENTINELS=redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
  #     - DOCKER_ENV=true
  #   networks:
  #     - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  mongo-data:
  redis-master-data: